# ---- input fasta file path ----
# use '--config genome=' at startup

# ---- paths ----
"out_dir": "./"
"trf_dir": "TRF/"
"repeatmasker_dir": "RepeatMasker/"
"windowmasker_dir": "WindowMasker/"

# ---- tool options ----
"RM_BASE": "carnivore"
"N_THREADS": 4
"TRF_PARAMETERS": "2 7 7 80 10 50 500"