# ---- input fasta file path ----
# use '--config genome=' at startup

# ---- input files ----
"genome": "genome.fasta"

# ---- paths ----
"genome_path": "./"
"out_dir": "./"
"trf_dir": "TRF/"
"repeatmasker_dir": "RepeatMasker/"
"windowmasker_dir": "WindowMasker/"

# ---- tool options ----
"repeatmasker_base": "carnivore"
"N_threads": 4
"TRF_parameters": "2 7 7 80 10 50 500"